vich_uploader:
    db_driver: orm

    mappings:
        users_avatars:
            uri_prefix: /images/users/avatars
            upload_destination: '%kernel.project_dir%/public/images/users/avatars'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
