2fa_login:
    path: /{_locale}/2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"
        _locale: '%defaultlocale%'
    requirements:
        _locale: '(en|fr)?'

2fa_login_check:
    path: /{_locale}/2fa_check
    defaults:
        _locale: '%defaultlocale%'
    requirements:
        _locale: '(en|fr)?'
